/*
 * This source file was generated by the Gradle 'init' task
 */
package b01;

public class App {
    public String getGreeting() {
        return "B01 Gradle und Spotless laufen.";
    }

    public String formatDemo(String name) {
        return "Hallo, " + name + "!";
    }

    public static void main(String[] args) {
        App app = new App();
        System.out.println(app.getGreeting());
        System.out.println(app.formatDemo("Prog2"));
    }
}
