/*
 * This source file was generated by the Gradle 'init' task
 */
package b01;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void formatDemoBuildsExpectedText() {
        App classUnderTest = new App();
        assertEquals("Hallo, Prog2!", classUnderTest.formatDemo("Prog2"));
    }
}
